// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZbxFhmFO858jcCTVUwQOu1GFANory7JM',
    appId: '1:822023463042:android:1cbe33559e90a2234f149b',
    messagingSenderId: '822023463042',
    projectId: 'interviewpreparation-7a2ea',
    databaseURL: 'https://interviewpreparation-7a2ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'interviewpreparation-7a2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEDZ5_kBmSuCBmazHj6vGbjYheXA89gg',
    appId: '1:822023463042:ios:75a9fb0b223f83fc4f149b',
    messagingSenderId: '822023463042',
    projectId: 'interviewpreparation-7a2ea',
    databaseURL: 'https://interviewpreparation-7a2ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'interviewpreparation-7a2ea.appspot.com',
    iosBundleId: 'com.example.interviewPreparation',
  );
}
